namespace Constants
{
    public enum INVENTORY{ /*EQUIP, INVENTORY, QUICKSLOT,*/ CAPACITY = 10 };

    public enum PROTOTYPE_ATTACK { BASIC, BROADSWORD, DAGGER, SLIME, PROTOTYPE_ATTACK_END };

    public enum EQUIP_SLOT { WEAPON, ARMOR, EQUIP_SLOT_END };

    public enum QUICK_SLOT { CAPACITY = 4 };

    public enum SUPPLIES { HEALING_POTION, IDENTIFY_SCROLL, ENCHANT_SCROLL, SUPPLIES_END };
}